package com.ntmi.support.dto;

import com.ntmi.support.model.TicketPriority;
import com.ntmi.support.model.TicketStatus;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

@Data
public class TicketDTO {
    private Long ticketId;
    private String subject;      // Now Auto-Generated by Backend (Read-only for Create)
    private String description;  // Optional
    private TicketStatus status;
    private TicketPriority priority;
    
    // IDs for linking (Frontend sends these)
    private Long categoryId;
    private Long typeId;
    
    // ✅ NEW: List of Base64 Image Strings (Max 5)
    // The frontend sends the images here
    private List<String> images;
    
    // Read-only fields (Backend sends these back)
    private String categoryName;
    private String typeName;
    private String branchName;
    private String createdBy;
    private LocalDateTime createdAt;

    private Long assetId;
    public Long getAssetId() { return assetId; }
    public void setAssetId(Long assetId) { this.assetId = assetId;}

}